--- 
- hosts: eks
  become: True 
  gather_facts: True

  tasks:
    - name: copy kubernetes latest definition file 
      template:
         src: /opt/build/workspace/zenda_test/ansible-k8s/templates/nodejs.yml.j2
         dest: /opt/nodejs.yml

    - name: deploy application      
      command: kubectl apply -f /opt/nodejs.yml 
